name: Hello 

on: 
  push: 
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: say Hello
        run: echo "Hello man hi"
